sources:
  patents:
    inpi:
      name: "Instituto Nacional da Propriedade Industrial"
      enabled: true

      datasets:
        buscaweb:
          enabled: true
          access: "bulk_files"
          years:
            - 2018
            - 2019
            - 2020

        badepi:
          enabled: true
          access: "bulk_file"
          version: "11.0"

  social_technologies:
    feac:
      name: "FEAC / Casa Hacker"
      enabled: true
      dataset: "tecnologias_sociais"
      access: "csv"
      reference_year: 2024
      scope: "Campinas, SP"